### ISSUE TITLE
Catch the error in case Kegg Rest API is not reachable

### ISSUE THREAD

**Issue by cfrioux** [ArnaudBelcour/kegg2bipartitegraph#1]
## Summary 
If the rest API of Kegg is not reachable, the error output of kegg2bipartite is not informative.
It could happen on clusters where access to the internet is restricted by default.

## Command line

```
kegg2bipartitegraph reconstruct_from_organism -o from_kegg_org -i mge
```

## Error
```
WARNING [bioservices.KEGG:596]:  status is not ok with Forbidden
status is not ok with Forbidden
WARNING [bioservices.KEGG:596]:  status is not ok with Forbidden
status is not ok with Forbidden
Traceback (most recent call last):
  File "/home/cfrioux/miniconda3/envs/kegg2bipartite/bin/kegg2bipartitegraph", line 33, in <module>
    sys.exit(load_entry_point('kegg2bipartitegraph', 'console_scripts', 'kegg2bipartitegraph')())
  File "/beegfs/cfrioux/code/kegg2bipartitegraph/kegg2bipartitegraph/__main__.py", line 186, in main
    create_organism_network(args.input, args.output)
  File "/beegfs/cfrioux/code/kegg2bipartitegraph/kegg2bipartitegraph/organism.py", line 76, in create_organism_network
    if KEGG_BIOSERVICES.isOrganism(organism) is not True:
  File "/home/cfrioux/miniconda3/envs/kegg2bipartite/lib/python3.10/site-packages/bioservices/kegg.py", line 329, in isOrganism
    if org in self.organismIds:
  File "/home/cfrioux/miniconda3/envs/kegg2bipartite/lib/python3.10/site-packages/bioservices/kegg.py", line 283, in __getattr__
    Ids = [x.split()[0] for x in res.split("\n") if len(x)]
AttributeError: 'int' object has no attribute 'split'
```

The warning helps but it is just a warning and for instance it does not prevent using `kegg2bipartitegraph reconstruct_from_eggnog`.

**Comment by FelixRoy** [comment]
# Summary

The error is still up, and happens on laptops as well with no Internet restriction. Indeed, following [EBAME tutorial](https://gitlab.inria.fr/cfrioux/ebame), `reconstruct_from_organism` fails due to the server not responding. It might also be a new API, as the answer changed from *Forbidden* to *Bad Request*. 

# Command line

`k2bg reconstruct_from_organism -i mge -o ebame/results/KEGG_metabolic_network_mge/`

# Error
```
|kegg2bipartitegraph|organism| Begin KEGG metabolism mapping for organism mge.
|kegg2bipartitegraph|organism| Use default reference KEGG model from /home/xxx/miniconda3/envs/ebame_metabo_reasoning/lib/python3.10/site-packages/kegg2bipartitegraph/data.
WARNING [bioservices.KEGG:596]:  status is not ok with Bad Request
status is not ok with Bad Request
WARNING [bioservices.KEGG:596]:  status is not ok with Bad Request
status is not ok with Bad Request
Traceback (most recent call last):
  File "/home/xxx/miniconda3/envs/ebame_metabo_reasoning/bin/k2bg", line 8, in <module>
    sys.exit(main())
  File "/home/xxx/miniconda3/envs/ebame_metabo_reasoning/lib/python3.10/site-packages/kegg2bipartitegraph/__main__.py", line 225, in main
    create_organism_network(args.input, args.output, args.reference_folder)
  File "/home/xxx/miniconda3/envs/ebame_metabo_reasoning/lib/python3.10/site-packages/kegg2bipartitegraph/organism.py", line 173, in create_organism_network
    if KEGG_BIOSERVICES.isOrganism(organism) is not True:
  File "/home/xxx/miniconda3/envs/ebame_metabo_reasoning/lib/python3.10/site-packages/bioservices/kegg.py", line 329, in isOrganism
    if org in self.organismIds:
  File "/home/xxx/miniconda3/envs/ebame_metabo_reasoning/lib/python3.10/site-packages/bioservices/kegg.py", line 283, in __getattr__
    Ids = [x.split()[0] for x in res.split("\n") if len(x)]
AttributeError: 'int' object has no attribute 'split'. Did you mean: '_organisms'?
```

**Comment by ArnaudBelcour** [comment]
Hi @FelixRoy,

Thanks for the issue. There are indeed two issues:

- (1) the case where a computer without internet connection return this error.
- (2) a change in API, I have found an issue with the API request of `list/organism` leading to this error and the `Bad Request`.

Sadly, I do not have a lot of time to put into kegg2bipartitegraph, so I am not sure to be able to handle issue (1) but for issue (2) I will try to find a solution. But as it is linked with another package (`bioservices`), this could take some time.

**Comment by FelixRoy** [comment]
Hi @ArnaudBelcour,

Thanks for the quick answer and the package 🙂 
No worries for the issue, I was just checking the tutorial; there is no rush on my side. Also, feel free to move the issue, as indeed it seems to be uncorrelated to the first one raised by cfrioux (sorry about that).

Cheers

**Comment by ArnaudBelcour** [comment]
Hi @FelixRoy,

I have made a fix on a fork of bioservices and a commit for kegg2bipartitegraph that should solve the different issues.

While waiting for the update to bioservices, if you want to check, you can install them with:
```
pip uninstall bioservices kegg2bipartitegraph
pip install git+https://github.com/ArnaudBelcour/bioservices.git@b388962123128743f449bc392ab335de75f832ed
pip install git+https://github.com/ArnaudBelcour/kegg2bipartitegraph.git@6a7531b292a098d58d2889f05544963f1a904f91
```

This should solve the issue on the tutorial.

I have also added a small function to check internet connection and KEGG API. I am not happy with it but it should work.

**Comment by FelixRoy** [comment]
Hi @ArnaudBelcour,

Indeed this solves the issue, congrats and thanks 🙂
I was considering updating the dependencies in the tutorial, but I reckon I'll wait for the merges to happen instead ^^
