### ISSUE TITLE
kegg2bipartitegraph not working for hsa

### ISSUE THREAD

**Issue by syprigen** [ArnaudBelcour/kegg2bipartitegraph#2]
### Summary
The automatic reconstruction of the human sbml file fails

### Command line
`k2bg reconstruct_from_organism -i hsa -o testHuman
`
### Error
```
|kegg2bipartitegraph|organism| Begin KEGG metabolism mapping for organism hsa.
|kegg2bipartitegraph|organism| Use default reference KEGG model from /var/lib/miniforge/envs/ebame_metabo_reasoning/lib/python3.10/site-packages/kegg2bipartitegraph/data.
|kegg2bipartitegraph|organism| Added 2772 reactions from 1449 EC for organism hsa.
Traceback (most recent call last):
  File "/var/lib/miniforge/envs/ebame_metabo_reasoning/bin/k2bg", line 8, in <module>
    sys.exit(main())
  File "/var/lib/miniforge/envs/ebame_metabo_reasoning/lib/python3.10/site-packages/kegg2bipartitegraph/__main__.py", line 225, in main
    create_organism_network(args.input, args.output, args.reference_folder)
  File "/var/lib/miniforge/envs/ebame_metabo_reasoning/lib/python3.10/site-packages/kegg2bipartitegraph/organism.py", line 309, in create_organism_network
    kegg_document, kegg_model = create_sbml_from_kegg_reactions(organism, reference_reactions, reference_species, reference_groups, taxon_reactions, organism_pathways, organism_modules)
  File "/var/lib/miniforge/envs/ebame_metabo_reasoning/lib/python3.10/site-packages/kegg2bipartitegraph/sbml.py", line 180, in create_sbml_from_kegg_reactions
    libsbml_check(gpr_association.setAssociation(' or '.join(genes), True, True), "set gpr: ")
  File "/var/lib/miniforge/envs/ebame_metabo_reasoning/lib/python3.10/site-packages/kegg2bipartitegraph/sbml.py", line 56, in libsbml_check
    raise TypeError(err_msg)
TypeError: Error encountered trying to set gpr: .LibSBML returned error code -3: "The requested action could not be performed. This can occur in a variety of contexts, such as passing a null object as a parameter in a situation where it does not make sense to permit a null object."
```

I tested for a few other species (both prokaryotes and eukaryotes), and hsa is the only one failing.

**Comment by ArnaudBelcour** [comment]
Hi @syprigen,

Thanks for the report!
I have made some tests and this error is due to the gene IDs associated with `hsa` being only numeric. I have made a temporary fix by adding a `g` character as a prefix for these gene IDs. This seems to fix this issue.
I have released it in the version `0.1.2` for kegg2bipartitegraph. Can you see if it solves the issue on your side?
